### PR TITLE
Prettier YAML

### PR DESCRIPTION
**Pull request by ddbeck**
This PR turns on prettier for YAML files in the repo, for consistent YAML indentation and the like.

### CODE REVIEW

**Comment by ddbeck** [comment]
This will conflict with #228 in some way (requiring a rebase here or there, whatever the merge order).

**Comment by ddbeck** [comment]
Rebased.

**Review by peterbe — APPROVED** [review]
The only flaw I see is that this is running under `npm run lint-js` (in Travis) which is now poorly named. We might Prettier check other stuff some day such as the CSS in the examples. 
Perhaps we just rename that script in package.json to `lint-code` :)

**Comment by ddbeck** [comment]
> Perhaps we just rename that script in package.json to `lint-code` :)

Good idea, @peterbe! Done.

**Review by peterbe — APPROVED** [review]

**Comment by ddbeck** [comment]
Fixed the build failure. Didn't catch dotfiles in my search for `npm run lint-js`

**Pull request merged**
