### PR TITLE
pin exact version of mdn-browser-compat-data

### PR DESCRIPTION
**Pull request by peterbe**
I know why it was `0.x` before. It's a relic from how kuma and kumascript works. It relies on this version marker so that every time you build a new Docker image of KumaScript it downloads the latest version. 

As of this change, as soon as a new version comes out, Dependabot will prepare a PR here and we immediately find out if that's going to work. Both here and with stumptown-renderer. 

My hope is that, within some limits, we might ship a whole new production site as soon as something merges to `master` here in this repo. That means, that minutes after BCD makes a new release, Dependabot makes a PR, and seconds/minutes after that's merged it would go out to developer.mozilla.org. 

And what's neat too is that we'd still be able to control that. Suppose that the format in BCD changes, we won't get nasty surprises because CI would hopefully break or we'd manually hold back the Dependabot PR.

### CODE REVIEW

**Comment by wbamberg** [comment]
I don't understand why this PR changes URLs in package-lock from https to http, and integrity hashes from SHA-512 to SHA-1.

**Comment by peterbe** [comment]
Good catch! And... what the heck!! 
I have `npm` version 6.11.3 and I ran:
```
npm install --save mdn-browser-compat-data@0.0.94
```

What happens to package-lock.json when you do that, from `master`, on your machine?
Also, can we switch to `yarn` tomorrow?

**Comment by wbamberg** [comment]
Yes, I don't understand it at all.

> What happens to package-lock.json when you do that, from master, on your machine?

I'm running npm 6.10.3, and I get:

```
--- a/package-lock.json
+++ b/package-lock.json
@@ -72,7 +72,7 @@
         },
         "ansi-escapes": {
             "version": "1.4.0",
-            "resolved": "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz",
+            "resolved": "http://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz",
             "integrity": "sha1-06ioOzGapneTZisT52HHkRQiMG4="
         },
         "ansi-regex": {
@@ -839,7 +839,7 @@
         },
         "external-editor": {
             "version": "1.1.1",
-            "resolved": "https://registry.npmjs.org/external-editor/-/external-editor-1.1.1.tgz",
+            "resolved": "http://registry.npmjs.org/external-editor/-/external-editor-1.1.1.tgz",
             "integrity": "sha1-Etew24UPf/fnCBuvQAVwAGDEYAs=",
             "requires": {
                 "extend": "^3.0.0",
@@ -1325,7 +1325,7 @@
         },
         "inquirer": {
             "version": "1.2.3",
-            "resolved": "https://registry.npmjs.org/inquirer/-/inquirer-1.2.3.tgz",
+            "resolved": "http://registry.npmjs.org/inquirer/-/inquirer-1.2.3.tgz",
             "integrity": "sha1-TexvMvN+97sLLtPx0aXD9UUHSRg=",
             "requires": {
                 "ansi-escapes": "^1.1.0",
@@ -1351,7 +1351,7 @@
                 },
                 "chalk": {
                     "version": "1.1.3",
-                    "resolved": "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz",
+                    "resolved": "http://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz",
                     "integrity": "sha1-qBFcVeSnAv5NFQq9OHKCKn4J/Jg=",
                     "requires": {
                         "ansi-styles": "^2.2.1",
@@ -1760,9 +1760,9 @@
             "integrity": "sha512-2qLt/DEOo5F6nc2VFScQiHPzQ0XXcabquRJxKMhKte8nt42o08HUxNDPk7tt0YPxnWjAT11I1SYi0X0iPnfI5A=="
         },
         "mdn-browser-compat-data": {
-            "version": "0.0.93",
-            "resolved": "https://registry.npmjs.org/mdn-browser-compat-data/-/mdn-browser-compat-data-0.0.93.tgz",
-            "integrity": "sha512-rrgjwkQOz/c9LMLMuTRslvkx0m3/BQdw8eCT4GB2vyApPClD6yxjzFJ37xzIfSLqiF0fQkFNGrW7MkzHoR8LjA==",
+            "version": "0.0.94",
+            "resolved": "https://registry.npmjs.org/mdn-browser-compat-data/-/mdn-browser-compat-data-0.0.94.tgz",
+            "integrity": "sha512-O3zJqbmehz0Hn3wpk62taA0+jNF7yn6BDWqQ9Wh2bEoO9Rx1BYiTmNX565eNVbW0ixfQkY6Sp9FvY/rr79Qmyg==",
             "requires": {
                 "extend": "3.0.2"
             }
@@ -1801,7 +1801,7 @@
         },
         "minimist": {
             "version": "1.2.0",
-            "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz",
+            "resolved": "http://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz",
             "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ="
         },
         "mkdirp": {
@@ -1907,7 +1907,7 @@
         },
         "onetime": {
             "version": "1.1.0",
-            "resolved": "https://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz",
+            "resolved": "http://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz",
             "integrity": "sha1-ofeDj4MUxRbwXs78vEzP4EtO14k="
         },
         "optionator": {
@@ -2917,7 +2917,7 @@
         },
         "strip-ansi": {
             "version": "3.0.1",
-            "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
+            "resolved": "http://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
             "integrity": "sha1-ajhfuIU9lS1f8F0Oiq+UJ43GPc8=",
             "requires": {
                 "ansi-regex": "^2.0.0"
```

...which looks like the same HTTPS->HTTP changes, but none of the SHA changes.

> Also, can we switch to yarn tomorrow?

Personally I'm happy to go with either. On the face of it I'd prefer us to use a single package manager across MDN projects, or at least I'd like divergence to be a thing we discuss and accept as a team.

**Comment by Gregoor** [comment]
My diff on Windows 10, Node 10.16.3, NPM 6.9.0

```
@@ -1786,9 +1786,9 @@
             "integrity": "sha512-2qLt/DEOo5F6nc2VFScQiHPzQ0XXcabquRJxKMhKte8nt42o08HUxNDPk7tt0YPxnWjAT11I1SYi0X0iPnfI5A=="
         },
         "mdn-browser-compat-data": {
-            "version": "0.0.93",
-            "resolved": "https://registry.npmjs.org/mdn-browser-compat-data/-/mdn-browser-compat-data-0.0.93.tgz",
-            "integrity": "sha512-rrgjwkQOz/c9LMLMuTRslvkx0m3/BQdw8eCT4GB2vyApPClD6yxjzFJ37xzIfSLqiF0fQkFNGrW7MkzHoR8LjA==",
+            "version": "0.0.94",
+            "resolved": "https://registry.npmjs.org/mdn-browser-compat-data/-/mdn-browser-compat-data-0.0.94.tgz",
+            "integrity": "sha512-O3zJqbmehz0Hn3wpk62taA0+jNF7yn6BDWqQ9Wh2bEoO9Rx1BYiTmNX565eNVbW0ixfQkY6Sp9FvY/rr79Qmyg==",
             "requires": {
                 "extend": "3.0.2"
             }
```

**Comment by peterbe** [comment]
3 different outcomes. We're all running different versions of `npm` which could explain things but it still sucks. And I'm not sure how to proceed. I could bulldozer up a PR to switch over to `yarn` but I'm afraid of getting stuck in a bikeshed about getting concensus. 
The https-to-http thing is apparently not a security risk. But having to run `git checkout package-lock.json` after every `cd stumptown-content && npm install` is counter-productive. 

I skimmed this fast and there's generally a lot of discontent about `npm` and the fact that the `package-lock.json` isn't deterministic in any sensible way. 
https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/49

**Review by wbamberg — APPROVED** [review]
All the weirdness aside, this seems like a good change.

**Pull request merged**
